name: Build and Publish Multi-Arch Docker Image

on:
  release:
    types: [created]  # Trigger the workflow when a release is created

jobs:
  build-amd64:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}  # Your Docker Hub username
        password: ${{ secrets.DOCKER_PASSWORD }}  # Your Docker Hub password or access token

    - name: Build and push AMD64 Docker image
      uses: docker/build-push-action@v3
      with:
        context: .
        push: true
        platforms: linux/amd64  # Specify AMD64 architecture
        tags: kokofixcomputers/docker-openssh-server-fork:latest  # Replace with your image name

  build-arm64:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}  # Your Docker Hub username
        password: ${{ secrets.DOCKER_PASSWORD }}  # Your Docker Hub password or access token

    - name: Build and push ARM64 Docker image
      uses: docker/build-push-action@v3
      with:
        context: .
        push: true
        platforms: linux/arm64  # Specify ARM64 architecture
        tags: kokofixcomputers/docker-openssh-server-fork:latest  # Replace with your image name
